version: '3'
services:
  php:
    build: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
